/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManualPunchRouteImport } from './routes/manual-punch'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PunchRouteImport } from './routes/punch'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as WarningsRouteImport } from './routes/warnings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualPunchRoute = ManualPunchRouteImport.update({
  id: '/manual-punch',
  path: '/manual-punch',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PunchRoute = PunchRouteImport.update({
  id: '/punch',
  path: '/punch',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const WarningsRoute = WarningsRouteImport.update({
  id: '/warnings',
  path: '/warnings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/employees': typeof EmployeesRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/manual-punch': typeof ManualPunchRoute
  '/payroll': typeof PayrollRoute
  '/punch': typeof PunchRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shifts': typeof ShiftsRoute
  '/warnings': typeof WarningsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/employees': typeof EmployeesRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/manual-punch': typeof ManualPunchRoute
  '/payroll': typeof PayrollRoute
  '/punch': typeof PunchRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shifts': typeof ShiftsRoute
  '/warnings': typeof WarningsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/employees': typeof EmployeesRoute
  '/leave': typeof LeaveRoute
  '/login': typeof LoginRoute
  '/manual-punch': typeof ManualPunchRoute
  '/payroll': typeof PayrollRoute
  '/punch': typeof PunchRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shifts': typeof ShiftsRoute
  '/warnings': typeof WarningsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/employees'
    | '/leave'
    | '/login'
    | '/manual-punch'
    | '/payroll'
    | '/punch'
    | '/reports'
    | '/settings'
    | '/shifts'
    | '/warnings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/employees'
    | '/leave'
    | '/login'
    | '/manual-punch'
    | '/payroll'
    | '/punch'
    | '/reports'
    | '/settings'
    | '/shifts'
    | '/warnings'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/employees'
    | '/leave'
    | '/login'
    | '/manual-punch'
    | '/payroll'
    | '/punch'
    | '/reports'
    | '/settings'
    | '/shifts'
    | '/warnings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  EmployeesRoute: typeof EmployeesRoute
  LeaveRoute: typeof LeaveRoute
  LoginRoute: typeof LoginRoute
  ManualPunchRoute: typeof ManualPunchRoute
  PayrollRoute: typeof PayrollRoute
  PunchRoute: typeof PunchRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ShiftsRoute: typeof ShiftsRoute
  WarningsRoute: typeof WarningsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-punch': {
      id: '/manual-punch'
      path: '/manual-punch'
      fullPath: '/manual-punch'
      preLoaderRoute: typeof ManualPunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/punch': {
      id: '/punch'
      path: '/punch'
      fullPath: '/punch'
      preLoaderRoute: typeof PunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warnings': {
      id: '/warnings'
      path: '/warnings'
      fullPath: '/warnings'
      preLoaderRoute: typeof WarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  EmployeesRoute: EmployeesRoute,
  LeaveRoute: LeaveRoute,
  LoginRoute: LoginRoute,
  ManualPunchRoute: ManualPunchRoute,
  PayrollRoute: PayrollRoute,
  PunchRoute: PunchRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ShiftsRoute: ShiftsRoute,
  WarningsRoute: WarningsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
